apiVersion: v1
kind: Service
metadata:
  labels:
    app: livy
  name: livy
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8998
  selector:
    app: livy
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: livy-server
  labels:
    app: livy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: livy
  template:
    metadata:
      labels:
        app: livy
    spec:
      containers:
      - name: livy-server
        image: brainlounge/livy-on-k8s-server:0.5.0-s2.4.0-h2.6
        imagePullPolicy: Always
        ports:
        - containerPort: 8998
          name: http
          protocol: TCP
        env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        securityContext:
          privileged: false

